name: ${PROJECT_NAME}

services:

  django:
    container_name: ${PROJECT_NAME}-django
    hostname: hs_django
    build:
      context: .
      dockerfile: Containerfile
    image: home-services-appserver:latest
    command: ./django-entrypoint.sh
    env_file:
      - .env
    volumes:
      - hs_shared_data:/home/app/web/shared
    networks:
      - reverse_proxy_net
      - db_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/admin/login/" ]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 30s
      retries: 10

  django-scheduler:
    container_name: ${PROJECT_NAME}-django-scheduler
    hostname: hs_scheduler
    build:
      context: .
      dockerfile: Containerfile
    image: home-services-appserver:latest
    command: python manage.py scheduler
    env_file:
      - .env
    volumes:
      - hs_shared_data:/home/app/web/shared
    networks:
      - db_net
    depends_on:
      django:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "find /tmp/scheduler_heartbeat.lock -mmin -1 | grep -q . || exit 1"]
      start_period: 5s
      start_interval: 5s
      interval: 30s
      timeout: 10s
      retries: 10

networks:
  reverse_proxy_net:
    external: true
    name: home-server_public_web
  db_net:
    external: true
    name: home-server_internal_db

volumes:
  hs_shared_data:
