# Generated by Django 5.2.7 on 2025-10-16 23:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status_check_interval', models.IntegerField(help_text='Interval in minutes to check the connection status')),
                ('speed_test_interval', models.IntegerField(help_text='Interval in minutes to perform speed tests')),
                ('mininum_hosts_to_ping', models.IntegerField(default=3, help_text='Minimum number of hosts to ping for status checks')),
                ('status_ping_error_unstable_threshold', models.DecimalField(decimal_places=2, default=0.3, help_text='Percentage of hosts with ping error to mark connection as unstable', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('status_ping_error_disconnected_threshold', models.DecimalField(decimal_places=2, default=0.7, help_text='Percentage of hosts with ping error to mark connection as disconnected', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('status_ping_success_connected_threshold', models.DecimalField(decimal_places=2, default=0.8, help_text='Percentage of hosts with successful ping to mark connection as connected', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('download_speed_minimun_threshold', models.FloatField(help_text='Minimum acceptable download speed in Mbps', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)])),
                ('download_speed_expected_threshold', models.FloatField(help_text='Expected download speed in Mbps', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)])),
                ('upload_speed_minimum_threshold', models.FloatField(help_text='Minimum acceptable upload speed in Mbps', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)])),
                ('upload_speed_expected_threshold', models.FloatField(help_text='Expected upload speed in Mbps', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)])),
                ('id_provider_speedtest', models.CharField(blank=True, help_text='Provider ID for speedtest.net (if applicable). https://williamyaps.github.io/wlmjavascript/servercli.html', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostsToPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hostname_or_ipaddress', models.CharField(help_text='Hostname or IP address to ping', max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts_to_ping', to='internet_status.internetprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('unstable', 'Unstable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('ping_results', models.JSONField(help_text='Ping results for the last check, including hosts with success and error.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_statuses', to='internet_status.internetprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.FloatField(help_text='Download speed in Mbps')),
                ('upload_speed', models.FloatField(help_text='Upload speed in Mbps')),
                ('latency', models.FloatField(help_text='Latency in ms')),
                ('last_tested', models.DateTimeField(auto_now=True)),
                ('full_results', models.JSONField(help_text='Full results from the speed test')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_speeds', to='internet_status.internetprovider')),
            ],
        ),
    ]
