# Generated by Django 6.0.2 on 2026-02-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetprovider',
            name='contracted_download_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Velocidade de download contratada junto à operadora.', max_digits=10, verbose_name='Download Contratado (Mbps)'),
        ),
        migrations.AddField(
            model_name='internetprovider',
            name='contracted_upload_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Velocidade de upload contratada junto à operadora.', max_digits=10, verbose_name='Upload Contratado (Mbps)'),
        ),
    ]
