# Generated by Django 6.0.2 on 2026-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_status', '0002_internetprovider_contracted_download_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetprovider',
            name='connection_alert_active',
            field=models.BooleanField(default=False, editable=False, help_text='Marcado automaticamente quando o alerta é enviado. Desmarcado quando a rede normaliza.', verbose_name='Alerta de Conexão Ativo'),
        ),
        migrations.AddField(
            model_name='internetprovider',
            name='connection_drop_limit',
            field=models.IntegerField(default=5, help_text='Número de testes de conectividade consecutivos com falha/instabilidade para disparar alerta.', verbose_name='Limite de Falhas de Conexão'),
        ),
        migrations.AddField(
            model_name='internetprovider',
            name='destination_emails',
            field=models.CharField(blank=True, help_text='Endereços de e-mail que receberão os alertas (separados por vírgula).', max_length=255, verbose_name='E-mails de Destino'),
        ),
        migrations.AddField(
            model_name='internetprovider',
            name='speed_alert_active',
            field=models.BooleanField(default=False, editable=False, help_text='Marcado automaticamente quando o alerta é enviado. Desmarcado quando a rede normaliza.', verbose_name='Alerta de Velocidade Ativo'),
        ),
        migrations.AddField(
            model_name='internetprovider',
            name='speed_drop_limit',
            field=models.IntegerField(default=3, help_text='Número de testes de velocidade consecutivos abaixo de 100Mbps para disparar alerta.', verbose_name='Limite de Quedas de Velocidade'),
        ),
    ]
