# Generated by Django 6.0.3 on 2026-03-08 01:28

import internet_status.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_status', '0003_internetprovider_connection_alert_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetprovider',
            name='speed_test_interval',
            field=models.CharField(default='0 * * * *', help_text="Ex: '0 * * * *' para a cada hora exata.", max_length=100, validators=[internet_status.models.validate_cron_expression], verbose_name='Frequência do Speedtest (CRON)'),
        ),
        migrations.AlterField(
            model_name='internetprovider',
            name='status_check_interval',
            field=models.CharField(default='*/5 * * * *', help_text="Ex: '*/5 * * * *' para a cada 5 min.", max_length=100, validators=[internet_status.models.validate_cron_expression], verbose_name='Frequência do Ping (CRON)'),
        ),
    ]
