# Generated by Django 6.0.3 on 2026-03-08 16:58

import django.core.validators
import internet_status.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_status', '0003_internetprovider_connection_alert_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetprovider',
            name='status_ping_error_disconnected_threshold',
        ),
        migrations.RemoveField(
            model_name='internetprovider',
            name='status_ping_error_unstable_threshold',
        ),
        migrations.RemoveField(
            model_name='internetprovider',
            name='status_ping_success_connected_threshold',
        ),
        migrations.AddField(
            model_name='hoststoping',
            name='check_type',
            field=models.CharField(choices=[('ICMP', 'ICMP Ping'), ('HTTP', 'HTTP 204 (Captive Portal)')], default='ICMP', help_text='Selecione HTTP para URLs de Portal Cativo ou ICMP para pings tradicionais.', max_length=4),
        ),
        migrations.AddField(
            model_name='internetprovider',
            name='unstable_latency_threshold',
            field=models.FloatField(default=150.0, help_text='Latência média máxima permitida antes de marcar a conexão como Instável.', validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Limite de Latência ICMP (ms)'),
        ),
        migrations.AddField(
            model_name='internetprovider',
            name='unstable_packet_loss_threshold',
            field=models.FloatField(default=30.0, help_text='Percentual máximo de perda de pacotes ICMP aceitável antes de marcar como Instável.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Limite de Perda de Pacotes (%)'),
        ),
        migrations.AlterField(
            model_name='hoststoping',
            name='hostname_or_ipaddress',
            field=models.CharField(help_text='Hostname/IP (para ICMP) ou URL completa (para HTTP, ex: http://clients3.google.com/generate_204)', max_length=255),
        ),
        migrations.AlterField(
            model_name='internetprovider',
            name='speed_test_interval',
            field=models.CharField(default='0 * * * *', help_text="Ex: '0 * * * *' para a cada hora exata.", max_length=100, validators=[internet_status.models.validate_cron_expression], verbose_name='Frequência do Speedtest (CRON)'),
        ),
        migrations.AlterField(
            model_name='internetprovider',
            name='status_check_interval',
            field=models.CharField(default='*/5 * * * *', help_text="Ex: '*/5 * * * *' para a cada 5 min.", max_length=100, validators=[internet_status.models.validate_cron_expression], verbose_name='Frequência do Ping (CRON)'),
        ),
    ]
