# Generated by Django 6.0.3 on 2026-03-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_status', '0004_remove_internetprovider_status_ping_error_disconnected_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpeedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('avg_download', models.FloatField(help_text='Média de download (Mbps) do dia')),
                ('avg_upload', models.FloatField(help_text='Média de upload (Mbps) do dia')),
                ('avg_latency', models.FloatField(help_text='Média de latência (ms) do dia')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_speed_summaries', to='internet_status.internetprovider')),
            ],
            options={
                'verbose_name': 'Resumo Diário de Velocidade',
                'verbose_name_plural': 'Resumos Diários de Velocidade',
                'unique_together': {('provider', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyStatusSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_checks', models.IntegerField(help_text='Total de verificações realizadas no dia')),
                ('connected_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de status CONNECTED', max_digits=5)),
                ('unstable_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de status UNSTABLE', max_digits=5)),
                ('disconnected_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de status DISCONNECTED', max_digits=5)),
                ('unknown_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de status UNKNOWN', max_digits=5)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_status_summaries', to='internet_status.internetprovider')),
            ],
            options={
                'verbose_name': 'Resumo Diário de Status',
                'verbose_name_plural': 'Resumos Diários de Status',
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
