# Generated by Django 6.0.3 on 2026-03-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_status', '0005_dailyspeedsummary_dailystatussummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetprovider',
            name='download_speed_expected_threshold',
        ),
        migrations.RemoveField(
            model_name='internetprovider',
            name='minimum_hosts_to_ping',
        ),
        migrations.RemoveField(
            model_name='internetprovider',
            name='unstable_latency_threshold',
        ),
        migrations.RemoveField(
            model_name='internetprovider',
            name='unstable_packet_loss_threshold',
        ),
        migrations.RemoveField(
            model_name='internetprovider',
            name='upload_speed_expected_threshold',
        ),
    ]
