# Generated by Django 6.0.3 on 2026-03-21 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_status', '0006_remove_internetprovider_download_speed_expected_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetprovider',
            name='download_speed_minimum_threshold',
            field=models.FloatField(help_text='Referência de velocidade de download mínima aceitável in Mbps.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='internetprovider',
            name='id_provider_speedtest',
            field=models.CharField(blank=True, help_text='ID do provedor do speedtest.net (se aplicável). https://williamyaps.github.io/wlmjavascript/servercli.html', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internetprovider',
            name='upload_speed_minimum_threshold',
            field=models.FloatField(help_text='Referência de velocidade de upload mínima aceitável in Mbps.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.CreateModel(
            name='MonthlyInternetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('avg_connectivity', models.FloatField(help_text='Percentual médio de conectividade')),
                ('avg_download', models.FloatField(help_text='Velocidade média de download (Mbps)')),
                ('avg_upload', models.FloatField(help_text='Velocidade média de upload (Mbps)')),
                ('download_pct_contracted', models.FloatField(help_text='% do download contratado')),
                ('upload_pct_contracted', models.FloatField(help_text='% do upload contratado')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='internet_status.internetprovider')),
            ],
            options={
                'verbose_name': 'Resumo Mensal de Internet',
                'verbose_name_plural': 'Resumos Mensais de Internet',
                'unique_together': {('provider', 'year', 'month')},
            },
        ),
    ]
